config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:new, :create, :destroy]
  resources :chats do
    resources :comments, only: [:create]
  end
  get 'search', to: 'chats#search'
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  
  root 'chats#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true
    scope :search, -> (keyword) {
    where("title ILIKE :keyword", keyword: "%#{keyword}%") if keyword.present?
  }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :chat
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :plan_id, scope: :user_id
  with_options presence: true do
    validates :user_id
    validates :customer_id
    validates :active_until
    validates :stripe_subscription_id
    validates :plan_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]
  
  has_many :chats, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :team, dependent: :destroy

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end

  def can_create_chat?
    if is_subscribed
      true
    else
      chats.count < 3
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
require "openai"
require 'dotenv'
Dotenv.load

  before_action :set_common_variable

  private

  # APIキーを設定
  def set_common_variable
    @client = OpenAI::Client.new(access_token: ENV["CHATGPT_API_KEY"])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]
  before_action :set_header
  before_action :authenticate_user!

  # GET /chats or /chats.json
def index
  if params[:keyword].present?
    @chats = current_user.chats.search(params[:keyword]).order(created_at: :desc)
  else
    @chats = current_user.chats.order(created_at: :desc)
  end
end

  # GET /chats/1 or /chats/1.json
  def show
    @comments = @chat.comments
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    if current_user.can_create_chat?
      @chat = current_user.chats.build(chat_params)

      if @chat.save
        redirect_to chat_url(@chat)
      else
        flash.now[:alert] = "タスクの作成に失敗しました"
        render :new
      end
    else
      redirect_to new_team_path, alert: "タスクの作成制限に達しました。サブスクリプションに登録して無制限のタスク作成を利用してください。"
    end
  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    def set_header
      @chats = Chat.all
    end
    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:title)
    end
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @chat = Chat.find(params[:chat_id])
    @comment = @chat.comments.build(comment_params)
    @comment.user = current_user
    @comment.gpt_response = fetch_gpt_response(@comment.content)

    if @comment.save
      respond_to do |format|
        format.js
        format.html { redirect_to @chat, notice: 'コメントを投稿しました。' }
      end
    else
      redirect_to @chat, alert: 'コメントの投稿に失敗しました。'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def fetch_gpt_response(user_input)
    @content = params[:content]

    response = @client.chat(
      parameters: {
          model: "gpt-3.5-turbo",
          messages: [{ role: "user", content: user_input }],
      })

    @chats = response.dig("choices", 0, "message", "content")
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
    @chats = Chat.all
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def line; basic_action end

  private
  def basic_action
    @omniauth = request.env["omniauth.auth"]
    if @omniauth.present?
      @profile = User.find_or_initialize_by(provider: @omniauth["provider"], uid: @omniauth["uid"])
      if @profile.email.blank?
        email = @omniauth["info"]["email"] ? @omniauth["info"]["email"] : "#{@omniauth["uid"]}-#{@omniauth["provider"]}@example.com"
        @profile = current_user || User.create!(provider: @omniauth["provider"], uid: @omniauth["uid"], email: email, name: @omniauth["info"]["name"], password: Devise.friendly_token[0, 20])
      end

      # プロフィール画像を取得
      profile_picture = @omniauth['info']['image']

      # ここでプロフィール画像を保存する処理を追加
      @profile.update(profile_picture: profile_picture)

      @profile.set_values(@omniauth)
      sign_in(:user, @profile)
    end
    flash[:notice] = "ログインしました"
    redirect_to root_path
  end

  def fake_email(uid, provider)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = current_user
    @team = Team.find_by(user_id: @user.id)
  end

  def create
    @team = Team.new(user_id: current_user.id)
    customer = Stripe::Customer.create({
      source: params[:stripeToken]
    })
    subscription = Stripe::Subscription.create({
      customer: customer.id,
      plan: "price_1MwiLIH9VISkxUuRHaqx9RPj"
    })
    @team.plan_id = "price_1MwiLIH9VISkxUuRHaqx9RPj"
    @team.customer_id = customer.id
    @team.stripe_subscription_id = subscription.id
    @team.active_until = Time.zone.at(subscription.current_period_end)
    if @team.save
      current_user.update(is_subscribed: true)
      flash[:notice] = "成功しました"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    current_user.update(is_subscribed: false)

    respond_to do |format|
      format.html { redirect_to chats_url, notice: "解約しました。" }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/chats/_form.html.erb
<div class="bg-gray-200">
  <%= link_to chats_path do %>
    <i class="fas fa-chevron-left text-xl m-4"></i>
  <% end %>
</div>
<div class="bg-gray-200 h-96 w-screen flex justify-center items-center">
  <div class="w-full max-w-xs">
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <%= form_with(model: chat) do |form| %>
        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-bold mb-2">
            タイトル
          </label>
          <%= form.text_field :title, :placeholder => "タイトルを入力...", :class => "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="flex items-center justify-between">
          <%= form.submit '新規作成', class: "bg-lime-500 hover:bg-lime-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
      <p class="text-center text-gray-500 text-xs">
        &copy;2020 Acme Corp. All rights reserved.
      </p>
    </div>
  </div>
</div>

app/views/chats/_header.html.erb
<header class="flex h-20 items-center border-y-2 p-6">
    <p class="font-sans font-bold text-lime-400 flex-auto w-64 m-1 p-1">Chat LINE</p>
    <div class="flex-auto w-64 m-1 p-1">
        <input id="menu-checkbox" type="checkbox" />
        <label class="menu-btn" for="menu-checkbox">
            <i class="fas fa-bars"></i>
        </label>
        <div class="nav-content">
            <input id="menu-checkbox" type="checkbox" />
            <label class="menu-btn" for="menu-checkbox">
                <i class="fas fa-times"></i>
            </label>
            <nav class="nav-menu">
                <%= link_to "+ New chat", new_chat_path, class: "py-2.5 px-8 mr-4 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" %>
                <hr>
                <div class="scroller bg-white py-3 h-96">
                    <div class="mx-auto max-w-lg">
                        <ul role="list" class="divide-y divide-gray-100">
                            <% @chats.each do |chat| %>
                                <li>
                                    <div class="flex items-center gap-x-3">
                                        <div class="flex-auto w-64 m-1 p-1">
                                            <%= link_to chat do %>
                                              <%= chat.title %>
                                            <% end %>
                                            <div class="flex-auto m-1 p-1">
                                                <div class="flex flex-row-reverse">
                                                    <div class="p-1">
                                                        <%= button_to chat, form: { data: { turbo_confirm: "削除しますか？" } }, method: :delete do %>
                                                            <i class="fas fa-trash"></i>
                                                        <% end %>
                                                    </div>
                                                    <div class="p-1">
                                                        <%= link_to edit_chat_path(chat) do %>
                                                            <i class="fas fa-edit"></i>
                                                        <% end %>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </nav>
            <hr>
            <div class="flex my-2 mx-2">
              <%= link_to new_team_path do %>
                <i class="far fa-user">マイページ</i>
              <% end %>
            </div>
            <div class="flex my-2 mx-2">
              <%= button_to destroy_user_session_path, form: { data: { turbo_confirm: "ログアウトしますか？" } }, method: :delete do %>
                <i class="fas fa-sign-out-alt">ログアウト</i>
              <% end %>
            </div>
        </div>
        <label class="nav-close" for="menu-checkbox"></label>
    </div>
</header>

app/views/chats/edit.html.erb
<div class="h-screen w-screen bg-gray-200">
  <%= render "header", chat: @chat %>
  <%= render "form", chat: @chat %>
</div>

app/views/chats/index.html.erb
<div class="h-screen w-screen bg-gray-200">
<%= render "header", chat: @chat %>
<div class="h-96 m-3">
  <%= link_to "+ New chat", new_chat_path, class: "py-2.5 px-8 mr-4 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700" %>
  <div class="flex mt-4">
    
    <%= form_with(url: chats_path, method: :get, local: true) do |form| %>
      <div class="search-form mx-2">
        <%= form.text_field :keyword, value: params[:keyword], placeholder: "キーワードを入力..." %>
        <%= form.submit '検索', class: "bg-lime-500 hover:bg-lime-700 text-white font-bold py-1 px-3 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>

    <div class="mx-2">
      <%= link_to chats_path do %>
        <i class="fas fa-redo-alt"></i>
      <% end %>  
    </div>
  </div>

  <ul role="list" class="mt-4 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
    <% @chats.each do |chat| %>
      <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
        <div class="flex w-full items-center justify-between space-x-6 p-6">
          <div class="flex-1 truncate">
            <div class="flex items-center space-x-3">
              <h3 class="truncate text-sm font-medium text-gray-900">
                <%= link_to chat do %>
                  <%= chat.title %>
                <% end %>
              </h3>
            </div>
          </div>
        </div>
        <div>
          <div class="-mt-px flex divide-x divide-gray-200">
            <div class="flex w-0 flex-1">
              <%= link_to edit_chat_path(chat), class: "relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-br-lg border border-transparent py-4 text-sm font-semibold text-gray-900" do %>
                <svg class="h-5 w-5 text-gray-400">
                  <i class="fas fa-edit"></i>
                </svg>
              <% end %>
            </div>
            <div class="-ml-px flex w-0 flex-1">
              <a class="relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-br-lg border border-transparent py-4 text-sm font-semibold text-gray-900">
                <%= button_to chat, form: { data: { turbo_confirm: "削除しますか？" } }, method: :delete do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              </a>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>
</div>
<footer class="bg-white">
  <div class="mx-auto max-w-7xl px-6 py-12 md:flex md:items-center md:justify-between lg:px-8">
    <div class="flex justify-center space-x-6 md:order-2">
      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Facebook</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Instagram</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">Twitter</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      </a>

      <a href="#" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">YouTube</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M19.812 5.418c.861.23 1.538.907 1.768 1.768C21.998 8.746 22 12 22 12s0 3.255-.418 4.814a2.504 2.504 0 0 1-1.768 1.768c-1.56.419-7.814.419-7.814.419s-6.255 0-7.814-.419a2.505 2.505 0 0 1-1.768-1.768C2 15.255 2 12 2 12s0-3.255.417-4.814a2.507 2.507 0 0 1 1.768-1.768C5.744 5 11.998 5 11.998 5s6.255 0 7.814.418ZM15.194 12 10 15V9l5.194 3Z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
    <div class="mt-8 md:order-1 md:mt-0">
      <p class="text-center text-xs leading-5 text-gray-500">&copy; 2020 Your Company, Inc. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/chats/new.html.erb
<div class="h-screen w-screen bg-gray-200">
  <%= render "header", chat: @chat %>
  <%= render "form", chat: @chat %>
</div>

app/views/chats/show.html.erb
<div class="bg-gray-200 h-screen flex flex-col">
  <%= render "header", chat: @chat %>
  <div class="w-full max-w-2xl mx-auto bg-white rounded-lg shadow-md overflow-hidden flex-1 flex flex-col">

    <p class="px-4 pt-4">
      <%= link_to chats_path do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
      <div class="flex justify-center">
        <div><%= @chat.title %></div>
      </div>
    </p>

    <div data-controller="autoscroll" class="scroller bg-gray-100 h-96 flex-1">
      <%= render @chat.comments %>
    </div>
    <hr>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="p-4">
  <div class="flex items-end justify-end mb-4">
    <div class="bg-line-green text-white text-sm font-semibold p-2 rounded-tl-lg rounded-tr-lg rounded-bl-lg">
      <%= comment.content %>
    </div>
  </div>
  <div class="flex items-end mb-4">
    <div class="bg-gray-300 text-gray-800 text-sm font-semibold p-2 rounded-tl-lg rounded-tr-lg rounded-br-lg">
      <%= comment.gpt_response %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="bg-gray-100 px-4 py-2">
    <%= form_with(model: [ @chat, @chat.comments.build ], remote: true) do |form| %>
        <div class="flex items-center">
            <%= form.text_field :content, :placeholder => "メッセージを入力...", :class => 'w-full px-3 py-2 text-sm text-gray-700 placeholder-gray-400 bg-white border-2 border-gray-300 rounded-lg focus:outline-none focus:border-blue-400' %>
            <%= form.submit "送信", class: "ml-2 px-4 py-2 text-sm text-white bg-line-green hover:bg-hover-line-green hover:bg-opacity-30 rounded-lg focus:outline-none focus:bg-blue-600" %>
        </div>
    <% end %>
</div>

app/views/comments/_gpt_response.html.erb
<div class="gpt-response">
  <%= comment.gpt_response %>
</div>

app/views/comments/_user_comment.html.erb
<div class="user-comment">
  <%= comment.content %>
</div>

app/views/comments/create.js.erb
var userComment = '<%= j render("comments/user_comment", comment: @comment) %>';
$("#comments").append(userComment);


var gptResponse = '<%= j render("comments/gpt_response", comment: @comment) %>';
$("#comments").append(gptResponse);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineChatgptRailsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/e55b6f04ff.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>